### ISSUE TITLE
Associated more than one accessory

### ISSUE THREAD

**Issue by leotordo** [espressif/esp-homekit-sdk#118]
If I've two identical boards may I use the same ID code (payload)?

When I do the association (with same or different ID) I've to power on a single accessory each time or I can supply both?

At the moment when I try to associate two boards both supplied sometimes somethings goes wrong

Thanks
Leo

**Comment by shahpiyushv** [comment]
If there are 2 accessories with the same setup info available for pairing at the same time, then one of the 2 will get chosen arbitrarily. You can either use  different values of `CONFIG_EXAMPLE_SETUP_ID` for the 2 accessories or follow the instructions for [HomeKit Setup Configuration](https://github.com/espressif/esp-homekit-sdk#homekit-setup-configuration) to generate unique credentials.

**Comment by leotordo** [comment]
thanks :-)
