### ISSUE TITLE
How to cleanly add or remove accessories ? (bridge)

### ISSUE THREAD

**Issue by ZweiEuro** [espressif/esp-homekit-sdk#121]
Hi! I want to try this out with a bridge. My bridge can dynamically add endpoints. 
I would think I can do this:

start HAP
...do other things
stop HAP
delete all accessories
re-add all now present acessories
start hap again

using delete_all_accessories and then readding doesn't work and causes a crash?
Stopping and then deleting all existing accessories (bridged) and then readding them causes any home app to lose any contact, restarting fixes this.

What is the right way of doing this? It seems everytime i  want to change the accessory i have to hard boot, is this really neccessary ?
What would be the correct process here ?

**Comment by shahpiyushv** [comment]
You can remove accessories using [hap_remove_bridged_accessory()](https://github.com/espressif/esp-homekit-sdk/blob/43bab6f68569e26c738f0273960200c809ec0ec9/components/homekit/esp_hap_core/include/hap.h#L543) and then delete them using [hap_acc_delete()](https://github.com/espressif/esp-homekit-sdk/blob/43bab6f68569e26c738f0273960200c809ec0ec9/components/homekit/esp_hap_core/include/hap.h#L553C6-L553C20) even without stopping HAP and then add them back as required.

**Comment by ZweiEuro** [comment]
I understand! thank you!
