### ISSUE TITLE
hap_platform_httpd_start failing

### ISSUE THREAD

**Issue by rokelber** [espressif/esp-homekit-sdk#127]
I am attempting to run the fan example, and it fails to run with `HTTPD START Failed [-1]`.  I have tracked down the issue to:

```
int hap_platform_httpd_start(httpd_handle_t *handle)
{
   httpd_config_t config = {
      ...
```

`config` initialization does not initialize all fields, resulting in the underlying call to `xTaskCreatePinnedToCoreWithCaps` failing.

**Comment by shahpiyushv** [comment]
Thanks for reporting the issue and providing the pointer to the fix. We will test this and push out updated code soon
