### ISSUE TITLE
Is it possible to remove nvs?

### ISSUE THREAD

**Issue by butaikis** [espressif/esp-homekit-sdk#128]
Hello. Is it possible to exclude the use of nvs storage in the SDK? There is no way to use nvs..

**Comment by shahpiyushv** [comment]
> There is no way to use nvs..

Not sure what you mean here. Why is there no way to use nvs?

esp_hap_core internally uses APIs from [hap_platform_keystore](https://github.com/espressif/esp-homekit-sdk/blob/master/components/homekit/esp_hap_platform/src/hap_platform_keystore.c) and not NVS directly. You can create your own abstraction here to skip nvs.
