### ISSUE TITLE
Change serial number without re-build source code

### ISSUE THREAD

**Issue by leotordo** [espressif/esp-homekit-sdk#134]
Hello,
 with lightbulb example I've to set specific value of setup-ID (when I add the accessory) and serial number (visibile in accessory properties in "Home").

For setup ID I use ./tools/factory_nvs_gen.py to generate a specific .bin file and it works fine.

Is there a .py for serial number? How to change app_main.c for using it?

Thanks
Stefano

**Comment by shahpiyushv** [comment]
The HomeKit SDK tools themselves cannot create serial numbers, but if you can create a CSV with serial numbers as per your requirements, you can use the [HomeKit Manufacturing Utility](https://github.com/espressif/esp-homekit-sdk/tree/master/tools/mfg_homekit) to add these in the factory nvs binary and read in your firmware code. Please also check the docs [here](https://github.com/espressif/esp-homekit-sdk?tab=readme-ov-file#homekit-setup-configuration)
