### ISSUE TITLE
Which sdk is best for me?

### ISSUE THREAD

**Issue by dguerri** [espressif/esp-homekit-sdk#20]
Hello and thanks for running this amazing community around ESP*.

I am evaluating both esp-homekit-sdk and esp-apple-homekit-adk but I am struggling to understand the reason why there are 2 projects with the same purpose and which one should I go for.

Could you please provide a comparison of the supported features for both projects?

Thanks!

**Comment by shahpiyushv** [comment]
@dguerri , can you check if this thread answers your questions: https://github.com/espressif/esp-homekit-sdk/issues/19? If it doesn't I can provide more information

**Comment by dguerri** [comment]
Yes indeed, #19 is very accurate and comprehensive. Thanks!
