### ISSUE TITLE
Remove service runtime

### ISSUE THREAD

**Issue by stefano055415** [espressif/esp-homekit-sdk#42]
I have an accessory with N services, is it possible to remove one more at runtime?

**Comment by shahpiyushv** [comment]
@stefano055415 , an API can be provided for that, but we haven't done so, since there wasn't any need for that. What's your use case?

**Comment by stefano055415** [comment]
I have a device that can be used as an outlet or as a switch, and can be configured at runtime, so when I change from switch to outlet, i would like to update the accessory on homekit

**Comment by shahpiyushv** [comment]
Better to set something in NVS and just reboot and set appropriate services? Even the category identifier can be correctly updated between HAP_CID_SWITCH/HAP_CID_OUTLET then.

Or implement accessory as a bridge and add/remove a switch/outlet as a bridged accessory as applicable?

**Comment by shahpiyushv** [comment]
@stefano055415 , Can you try calling `hap_update_config_number()` after you reboot into the firmware wherein the services have changed? Did you try the bridge option?

**Comment by stefano055415** [comment]
Ok I found the problem.
On the function:
hap_acc_t * hap_acc_create (hap_acc_cfg_t * acc_cfg) 
next_iid is fixed at 1

if I change the service from switch to outlet and reboot it doesn't work.
but if I increase the next_iid = 100, for example, and reboot everything works fine.

is it possible to implement this fix in the next update?
Thank you

**Comment by stefano055415** [comment]
ok thanks I try to see if so I can solve for the moment.

if you want as soon as you are able to introduce this new function, I would be happy to be able to test it

**Comment by stefano055415** [comment]
with this patch, everything seems to work.

I just made a small change

void hap_acc_set_next_iid (hap_acc_t * ha, uint32_t next_iid)
{
  if (ha) {
    ((__hap_acc_t *) ha) -> next_iid = ((__hap_acc_t *) ha) -> next_iid + next_iid;
  }
}

every time I make a change (from switch to outlet for example), I increase a value and save it in nvs.
on next reboot I use this value to keep the iids unchanged

accessory = hap_acc_create(&cfg);
hap_acc_set_next_iid(accessory, nvs_read_config_version());

**Comment by shahpiyushv** [comment]
@stefano055415 Changing the API as above would be too use case specific and non deterministic. Setting a fixed value for next_iid would suit even those use cases wherein services may have changed across fw upgrades, but the iid values need to be retained as per HAP requirements. Since value of next_iid after calling `hap_acc_create()` would be the same each time, wouldn't it be convenient if you manage that offset in your app, instead of doing it inside the API?

**Comment by stefano055415** [comment]
ok I understand, however for my needs it is fine.
I call the function N times and it works.

I have another problem with apple tests.

<img width="827" alt="Schermata 2021-05-14 alle 09 24 28" src="https://user-images.githubusercontent.com/4798738/118236441-5e974c80-b496-11eb-8821-91beecae59b2.png">

Could you help me?

**Comment by shahpiyushv** [comment]
@stefano055415 , are you working on a commercial HomeKit product? If yes, as indicated in the [README](https://github.com/espressif/esp-homekit-sdk/blob/master/README.md), please get in touch with us [here](https://www.espressif.com/en/products/sdks/esp-homekit-sdk) to get access to the MFi variant of the SDK. The above tests would pass with that.

Moreover, please also get your use case confirmed from Apple. I am not sure if they would allow this runtime service change.

**Comment by stefano055415** [comment]
ok thanks, I proceeded to make the request.
