### ISSUE TITLE
Setup ID absent

### ISSUE THREAD

**Issue by dev-err418** [espressif/esp-homekit-sdk#53]
When following the "HomeKit Setup Configuration", using ./factory_nvs_gen.py and esptool.py, I have an error, when the esp8266 finished reset : 
![Screen Shot 2021-06-04 at 2 51 44 PM](https://user-images.githubusercontent.com/59390256/120804050-7c5f4b00-c544-11eb-8255-3f44cf10478f.png)
Am I doing something wrong ?

**Comment by shahpiyushv** [comment]
@arthur-spa ,sorry for the late reply? Were you able to go beyond this? Can you tell us the exact steps you followed? Can you share the binary generated using the `factory_nvs_gen` tool?

**Comment by IsukaChiyogami** [comment]
I have the same problem ， could you share how you solve ？

**Comment by IsukaChiyogami** [comment]
I got it in the source code (components\homekit\esp_hap_core\src\esp_hap_setup_payload.c)
```
    if (strlen(setup_code) != 10 || strlen(setup_id) != 4) {
        ESP_LOGE(TAG, "Setup code or Setup ID not correct. Eg. 111-22-333, ES32");
```
the lenght of setup_id should be 4

**Comment by shahpiyushv** [comment]
Closing this issue as there was no update on this. This seems to be an issue of not flashing the factory_nvs binary at correct location
