### ISSUE TITLE
menuconfig 74880 >>115200

### ISSUE THREAD

**Issue by exrector** [espressif/esp-homekit-sdk#70]
There is a need to change the values manually in the file.

**Comment by shahpiyushv** [comment]
@exrector , can you elaborate a bit more on what exactly the issue is?

**Comment by exrector** [comment]
@shahpiyushv 
every time make menuconfig I set all the values to 115200
make flash-all OK
monitor-nothing is clear, garbage
I check sdkconfig and do autocorrect 74880 >> 115200
make flash-all OK
monitor-all OK

I can give you more details but tomorrow

**Comment by shahpiyushv** [comment]
Closing this as no further information was received
