### ISSUE TITLE
Failed to resolve component 'libsodium'

### ISSUE THREAD

**Issue by heartbreaker0** [espressif/esp-homekit-sdk#84]
I get this error when I tried to build the fan example. I'm using esp-idf 4.4 under Ubuntu21.04 and I installed libsodium via apt and compilation.
![Screenshot from 2022-02-15 01-48-53](https://user-images.githubusercontent.com/48881427/153919071-712dd6cc-8ef0-4a5b-8a0f-72c4e86fff8b.png)
 Thanks for your help.

**Comment by WallXiaoming** [comment]
I have the same problem. How you solve it? thanks

**Comment by WallXiaoming** [comment]
> I get this error when I tried to build the fan example. I'm using esp-idf 4.4 under Ubuntu21.04 and I installed libsodium via apt and compilation. ![Screenshot from 2022-02-15 01-48-53](https://user-images.githubusercontent.com/48881427/153919071-712dd6cc-8ef0-4a5b-8a0f-72c4e86fff8b.png) Thanks for your help.

I have the same problem. How you solve it? thanks

**Comment by Roelof626** [comment]
For me too, really want to solve it. already tried several things to build the project successfully...

**Comment by shahpiyushv** [comment]
@Roelof626 @WallXiaoming , for the time being,  I would recommend that you use release/v4.4 (or an other release/v4.x) branch of esp-idf instead of the master branch. The master branch has moved on to 5.0, which may not be backward compatible with 4.x.
