### ISSUE TITLE
WAC need MFi ?

### ISSUE THREAD

**Issue by VtechRay** [espressif/esp-homekit-sdk#89]
Hi,
I am using non commerial  homekit sdk from the https://github.com/espressif/esp-homekit-sdk.

Can I still test the WAC feature without WFi ?

**Comment by shahpiyushv** [comment]
@VtechRay , no you cannot. We have open sourced only those features that Apple has opened up in their HAP Specs and added in their open source ADK. WAC is not part of that.

**Comment by shahpiyushv** [comment]
Closing this issue as it has been answered.
